// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPMWSGIZyK3eZDDn1ZytuZNJu7UnTCWo',
    appId: '1:995313936622:android:f28a6a447f7001c0a0abff',
    messagingSenderId: '995313936622',
    projectId: 'transporation-app-b5f26',
    storageBucket: 'transporation-app-b5f26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw7NxwYFZmBFHBgbhREJxf69EV_37a5K4',
    appId: '1:995313936622:ios:688144fef98f175fa0abff',
    messagingSenderId: '995313936622',
    projectId: 'transporation-app-b5f26',
    storageBucket: 'transporation-app-b5f26.firebasestorage.app',
    iosBundleId: 'com.alsabiqoon.transportation',
  );

  /// Check if Firebase is configured
  static bool get isConfigured {
    try {
      final options = currentPlatform;
      return options.apiKey.isNotEmpty && options.appId.isNotEmpty;
    } catch (_) {
      return false;
    }
  }
}
